/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ClienteController;
import controller.TimeController;
import interdisciplinar.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author yurib
 */
public class InicioLogado extends javax.swing.JFrame {

    /**
     * Creates new form InicioLogado
     */
    public InicioLogado(String nomeCliente) {
        initComponents();
        NomeCliente.setText(nomeCliente);
    try {
        Cliente cliente = Cliente.clienteLogado;
        //String nomeTime = cliente.getNomeTime();

        TimeController timeController = new TimeController();
        Time time = timeController.buscarPorNome(cliente.getNomeTime());
        
        if (time != null) {
         String caminhoImagem = time.getBrasao(); // ex: imagens/flamengo.png
            ImageIcon icon = new ImageIcon(getClass().getResource("/" + caminhoImagem));
            Image img = icon.getImage().getScaledInstance(Brasao.getWidth(), Brasao.getHeight(), Image.SCALE_SMOOTH);
            Brasao.setIcon(new ImageIcon(img));
        } else {
            System.out.println("Time não encontrado.");
        }
    } catch (Exception e) {
        System.out.println("Erro ao carregar imagem do time: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeCliente = new javax.swing.JLabel();
        TelaExcluir = new javax.swing.JButton();
        TelaEditar = new javax.swing.JButton();
        Sobre = new javax.swing.JButton();
        Brasao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeCliente.setText("----------------------------------------------------------------------------");

        TelaExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelaExcluir.setText("Excluir");
        TelaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaExcluirActionPerformed(evt);
            }
        });

        TelaEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelaEditar.setText("Editar");
        TelaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaEditarActionPerformed(evt);
            }
        });

        Sobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });

        Brasao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Brasao.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(NomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelaExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(TelaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(TelaEditar)
                .addGap(37, 37, 37)
                .addComponent(TelaExcluir)
                .addGap(32, 32, 32)
                .addComponent(Sobre)
                .addGap(129, 129, 129))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaExcluirActionPerformed
        Excluir telaExcluir = new Excluir();
        telaExcluir.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TelaExcluirActionPerformed

    private void TelaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaEditarActionPerformed
        Editar telaEditar = new Editar();
        telaEditar.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TelaEditarActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        Sobre tela = new Sobre();
        tela.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioLogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioLogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioLogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioLogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            Cliente cliente = new Cliente();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brasao;
    private javax.swing.JLabel NomeCliente;
    private javax.swing.JButton Sobre;
    private javax.swing.JButton TelaEditar;
    private javax.swing.JButton TelaExcluir;
    // End of variables declaration//GEN-END:variables
}
