/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.DAOCliente;
import controller.ClienteController;
import interdisciplinar.Cliente;
import java.util.List;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author yurib
 */
public class Listagem extends javax.swing.JFrame {

    /**
     * Creates new form Listagem
     */
    public Listagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        ADM = new javax.swing.JButton();
        cliente = new javax.swing.JButton();
        ClienteId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lista.setText("Clique para mostrar");
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(Lista);

        excluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        excluir.setText("Exluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        ADM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ADM.setText("ADM");
        ADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMActionPerformed(evt);
            }
        });

        cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        ClienteId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Id do usuario:");

        Voltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 51, 51));
        Voltar.setText("Voltar");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(excluir)
                                .addGap(137, 137, 137)
                                .addComponent(ADM)
                                .addGap(124, 124, 124)
                                .addComponent(cliente))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Voltar)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADM)
                    .addComponent(cliente)
                    .addComponent(excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Voltar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseEntered
    try {
    DAOCliente dao = new DAOCliente();
    List<Cliente> clientes = dao.listar();

    StringBuilder texto = new StringBuilder();
    for (Cliente c : clientes) {
       texto.append("ID: ").append(c.getIdCliente())
             .append(" | Email: ").append(c.getEmail())
             .append(" | Nome: ").append(c.getNome())
             .append(" | Senha: ").append(c.getCSenha())
             .append(" | Permissão: ").append(c.getPermissao())
             .append(" | NomeTime: ").append(c.getNomeTime())
             .append("<br>");
    }

    Lista.setText("<html>" + texto.toString() + "</html>");

} catch (SQLException e) {
    e.printStackTrace();
    Lista.setText("Erro ao carregar clientes.");
}    // TODO add your handling code here:
    }//GEN-LAST:event_ListaMouseEntered

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
    ClienteController controller = new ClienteController();
        int resposta = JOptionPane.showConfirmDialog(
        null,
        "Deseja mesmo excluir?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION);

    if (resposta == JOptionPane.YES_OPTION) {
        int idSelecionado = Integer.parseInt(ClienteId.getText());
        boolean sucesso = controller.excluirById(idSelecionado);
        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Usuário excluído!");
                this.dispose();
    Listagem novaTela = new Listagem();
    novaTela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao excluir usuário.");
        }
    }
    }//GEN-LAST:event_excluirActionPerformed

    private void ADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMActionPerformed
    ClienteController controller = new ClienteController();
    try {
        int Id = Integer.parseInt(ClienteId.getText());
        boolean sucesso = controller.permitirById(Id, "1");

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Permissão concedida.");
            this.dispose();
            new Listagem().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao conceder permissão.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "ID inválido.");
    }
    }//GEN-LAST:event_ADMActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        ClienteController controller = new ClienteController();
        try {
        int Id = Integer.parseInt(ClienteId.getText());
        boolean sucesso = controller.permitirById(Id, "null");

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Permissão removida.");
            this.dispose();
            new Listagem().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao remover permissão.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "ID inválido.");
    }
    }//GEN-LAST:event_clienteActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        TelaADM tela = new TelaADM(Cliente.clienteLogado.getNome());
        tela.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADM;
    private javax.swing.JTextField ClienteId;
    private javax.swing.JLabel Lista;
    private javax.swing.JLabel Voltar;
    private javax.swing.JButton cliente;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
