/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ClienteController;
import controller.TimeController;
import interdisciplinar.Cliente;
import interdisciplinar.Time;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author yurib
 */
public class TelaADM extends javax.swing.JFrame {

    /**
     * Creates new form TelaADM
     */
    public TelaADM(String nomeCliente) {
        initComponents();
        ADM.setText(nomeCliente);        
    try {
        ClienteController clienteController = new ClienteController();
        Cliente cliente = clienteController.buscarTime(nomeCliente);
        
        TimeController timeController = new TimeController();
        Time time = timeController.buscarPorNome(cliente.getNomeTime());
            
        String caminhoImagem = time.getBrasao();
        ImageIcon icon = new ImageIcon(getClass().getResource("/"+caminhoImagem));
        Image img = icon.getImage().getScaledInstance(Brasao.getWidth(), Brasao.getHeight(), Image.SCALE_SMOOTH);
        Brasao.setIcon(new ImageIcon(img));
    } catch (Exception e) {
        System.out.println("Erro ao carregar imagem do time: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lista = new javax.swing.JButton();
        ADM = new javax.swing.JLabel();
        TelaCliente = new javax.swing.JButton();
        Brasao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lista.setText("Lista");
        Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaActionPerformed(evt);
            }
        });

        ADM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ADM.setText("-------------------------------------------------------------------------------");

        TelaCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TelaCliente.setText("Cliente");
        TelaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaClienteActionPerformed(evt);
            }
        });

        Brasao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Brasao.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ADM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TelaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ADM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Brasao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(Lista)
                .addGap(55, 55, 55)
                .addComponent(TelaCliente)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaActionPerformed
        Listagem tela = new Listagem();
        tela.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_ListaActionPerformed

    private void TelaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaClienteActionPerformed
    InicioLogado telaUsuario = new InicioLogado(Cliente.clienteLogado.getNome());
    telaUsuario.setVisible(true);
    TelaADM.this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TelaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADM;
    private javax.swing.JLabel Brasao;
    private javax.swing.JButton Lista;
    private javax.swing.JButton TelaCliente;
    // End of variables declaration//GEN-END:variables
}
